/*
Name: Shayan 
Date: June 8th, 2022
Description: a clone of the minesweeper game.
 */
package minesweeper;

import java.awt.Color;
import java.awt.event.MouseEvent;
import javax.swing.JButton;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.awt.Dimension;

public class Minesweeper extends javax.swing.JFrame {
    // Global variables

    // Two 8x8 matrices, one will store the position of the buttons and 
    // the other one will store the position of the mines on the board.
    JButton[][] board = new JButton[8][8];
    boolean[][] mineField = new boolean[8][8];

    // Variable to keep track of the number of flags the user can place
    int numFlags = 10;

    // Variable to keep track of how many safe blocks there are 
    int safeBlocks = 54;

    // Variable to determine if it is the user's first move
    boolean firstMove = true;

    // Icon objects for the flag and bomb images
    Icon flagIcon, bombIcon;

    /**
     * Creates new form JizanMinesweeper
     */
    public Minesweeper() {
        initComponents();

        // Fill the board matrix with all the buttons
        board[0][0] = btn00;
        board[0][1] = btn01;
        board[0][2] = btn02;
        board[0][3] = btn03;
        board[0][4] = btn04;
        board[0][5] = btn05;
        board[0][6] = btn06;
        board[0][7] = btn07;

        board[1][0] = btn10;
        board[1][1] = btn11;
        board[1][2] = btn12;
        board[1][3] = btn13;
        board[1][4] = btn14;
        board[1][5] = btn15;
        board[1][6] = btn16;
        board[1][7] = btn17;

        board[2][0] = btn20;
        board[2][1] = btn21;
        board[2][2] = btn22;
        board[2][3] = btn23;
        board[2][4] = btn24;
        board[2][5] = btn25;
        board[2][6] = btn26;
        board[2][7] = btn27;

        board[3][0] = btn30;
        board[3][1] = btn31;
        board[3][2] = btn32;
        board[3][3] = btn33;
        board[3][4] = btn34;
        board[3][5] = btn35;
        board[3][6] = btn36;
        board[3][7] = btn37;

        board[4][0] = btn40;
        board[4][1] = btn41;
        board[4][2] = btn42;
        board[4][3] = btn43;
        board[4][4] = btn44;
        board[4][5] = btn45;
        board[4][6] = btn46;
        board[4][7] = btn47;

        board[5][0] = btn50;
        board[5][1] = btn51;
        board[5][2] = btn52;
        board[5][3] = btn53;
        board[5][4] = btn54;
        board[5][5] = btn55;
        board[5][6] = btn56;
        board[5][7] = btn57;

        board[6][0] = btn60;
        board[6][1] = btn61;
        board[6][2] = btn62;
        board[6][3] = btn63;
        board[6][4] = btn64;
        board[6][5] = btn65;
        board[6][6] = btn66;
        board[6][7] = btn67;

        board[7][0] = btn70;
        board[7][1] = btn71;
        board[7][2] = btn72;
        board[7][3] = btn73;
        board[7][4] = btn74;
        board[7][5] = btn75;
        board[7][6] = btn76;
        board[7][7] = btn77;

        // Loop through each button in the 8x8 matrix
        for (int i = 0; i < 8; i++) {
            for (int j = 0; j < 8; j++) {
                // Set the color of each button to green
                board[i][j].setBackground(Color.GREEN);
            }
        }

        // Load the flag.png and bomb.png into the program
        flagIcon = new ImageIcon("src/minesweeper/flag.png");
        bombIcon = new ImageIcon("src/minesweeper/bomb.png");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblTitle = new javax.swing.JLabel();
        MenuBar = new javax.swing.JPanel();
        lblFlags = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblInstructions = new javax.swing.JLabel();
        tileGrid = new javax.swing.JPanel();
        btn30 = new javax.swing.JButton();
        btn31 = new javax.swing.JButton();
        btn32 = new javax.swing.JButton();
        btn33 = new javax.swing.JButton();
        btn34 = new javax.swing.JButton();
        btn35 = new javax.swing.JButton();
        btn36 = new javax.swing.JButton();
        btn37 = new javax.swing.JButton();
        btn40 = new javax.swing.JButton();
        btn41 = new javax.swing.JButton();
        btn42 = new javax.swing.JButton();
        btn43 = new javax.swing.JButton();
        btn44 = new javax.swing.JButton();
        btn45 = new javax.swing.JButton();
        btn46 = new javax.swing.JButton();
        btn47 = new javax.swing.JButton();
        btn50 = new javax.swing.JButton();
        btn51 = new javax.swing.JButton();
        btn52 = new javax.swing.JButton();
        btn53 = new javax.swing.JButton();
        btn54 = new javax.swing.JButton();
        btn55 = new javax.swing.JButton();
        btn56 = new javax.swing.JButton();
        btn57 = new javax.swing.JButton();
        btn60 = new javax.swing.JButton();
        btn61 = new javax.swing.JButton();
        btn62 = new javax.swing.JButton();
        btn63 = new javax.swing.JButton();
        btn64 = new javax.swing.JButton();
        btn65 = new javax.swing.JButton();
        btn66 = new javax.swing.JButton();
        btn67 = new javax.swing.JButton();
        btn70 = new javax.swing.JButton();
        btn71 = new javax.swing.JButton();
        btn72 = new javax.swing.JButton();
        btn73 = new javax.swing.JButton();
        btn74 = new javax.swing.JButton();
        btn75 = new javax.swing.JButton();
        btn76 = new javax.swing.JButton();
        btn77 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        btn23 = new javax.swing.JButton();
        btn24 = new javax.swing.JButton();
        btn25 = new javax.swing.JButton();
        btn26 = new javax.swing.JButton();
        btn27 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        btn17 = new javax.swing.JButton();
        btn00 = new javax.swing.JButton();
        btn01 = new javax.swing.JButton();
        btn02 = new javax.swing.JButton();
        btn03 = new javax.swing.JButton();
        btn04 = new javax.swing.JButton();
        btn05 = new javax.swing.JButton();
        btn06 = new javax.swing.JButton();
        btn07 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Minesweeper");
        setMinimumSize(new java.awt.Dimension(533, 647));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitle.setText("Minesweeper");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        lblFlags.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFlags.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minesweeper/flag.png"))); // NOI18N
        lblFlags.setText("Flags: 10");

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblInstructions.setText("        *Left click to clear block                 *Right click to place or remove flag");

        javax.swing.GroupLayout MenuBarLayout = new javax.swing.GroupLayout(MenuBar);
        MenuBar.setLayout(MenuBarLayout);
        MenuBarLayout.setHorizontalGroup(
            MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuBarLayout.createSequentialGroup()
                .addGroup(MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuBarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblInstructions, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE))
                    .addGroup(MenuBarLayout.createSequentialGroup()
                        .addComponent(lblFlags, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        MenuBarLayout.setVerticalGroup(
            MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuBarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFlags, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(MenuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 470, 90));

        tileGrid.setMaximumSize(new java.awt.Dimension(272, 296));
        tileGrid.setMinimumSize(new java.awt.Dimension(272, 296));
        tileGrid.setPreferredSize(new java.awt.Dimension(272, 296));
        tileGrid.setLayout(new java.awt.GridBagLayout());

        btn30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn30.setMaximumSize(new java.awt.Dimension(59, 35));
        btn30.setMinimumSize(new java.awt.Dimension(59, 35));
        btn30.setPreferredSize(new java.awt.Dimension(59, 35));
        btn30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn30MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn30, gridBagConstraints);

        btn31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn31.setMaximumSize(new java.awt.Dimension(59, 35));
        btn31.setMinimumSize(new java.awt.Dimension(59, 35));
        btn31.setPreferredSize(new java.awt.Dimension(59, 35));
        btn31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn31MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn31, gridBagConstraints);

        btn32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn32.setMaximumSize(new java.awt.Dimension(59, 35));
        btn32.setMinimumSize(new java.awt.Dimension(59, 35));
        btn32.setPreferredSize(new java.awt.Dimension(59, 35));
        btn32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn32MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn32, gridBagConstraints);

        btn33.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn33.setMaximumSize(new java.awt.Dimension(59, 35));
        btn33.setMinimumSize(new java.awt.Dimension(59, 35));
        btn33.setPreferredSize(new java.awt.Dimension(59, 35));
        btn33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn33MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn33, gridBagConstraints);

        btn34.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn34.setMaximumSize(new java.awt.Dimension(59, 35));
        btn34.setMinimumSize(new java.awt.Dimension(59, 35));
        btn34.setPreferredSize(new java.awt.Dimension(59, 35));
        btn34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn34MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn34, gridBagConstraints);

        btn35.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn35.setMaximumSize(new java.awt.Dimension(59, 35));
        btn35.setMinimumSize(new java.awt.Dimension(59, 35));
        btn35.setPreferredSize(new java.awt.Dimension(59, 35));
        btn35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn35MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn35, gridBagConstraints);

        btn36.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn36.setMaximumSize(new java.awt.Dimension(59, 35));
        btn36.setMinimumSize(new java.awt.Dimension(59, 35));
        btn36.setPreferredSize(new java.awt.Dimension(59, 35));
        btn36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn36MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn36, gridBagConstraints);

        btn37.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn37.setMaximumSize(new java.awt.Dimension(59, 35));
        btn37.setMinimumSize(new java.awt.Dimension(59, 35));
        btn37.setPreferredSize(new java.awt.Dimension(59, 35));
        btn37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn37MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn37, gridBagConstraints);

        btn40.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn40.setMaximumSize(new java.awt.Dimension(59, 35));
        btn40.setMinimumSize(new java.awt.Dimension(59, 35));
        btn40.setPreferredSize(new java.awt.Dimension(59, 35));
        btn40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn40MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn40, gridBagConstraints);

        btn41.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn41.setMaximumSize(new java.awt.Dimension(59, 35));
        btn41.setMinimumSize(new java.awt.Dimension(59, 35));
        btn41.setPreferredSize(new java.awt.Dimension(59, 35));
        btn41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn41MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn41, gridBagConstraints);

        btn42.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn42.setMaximumSize(new java.awt.Dimension(59, 35));
        btn42.setMinimumSize(new java.awt.Dimension(59, 35));
        btn42.setPreferredSize(new java.awt.Dimension(59, 35));
        btn42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn42MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn42, gridBagConstraints);

        btn43.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn43.setMaximumSize(new java.awt.Dimension(59, 35));
        btn43.setMinimumSize(new java.awt.Dimension(59, 35));
        btn43.setPreferredSize(new java.awt.Dimension(59, 35));
        btn43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn43MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn43, gridBagConstraints);

        btn44.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn44.setMaximumSize(new java.awt.Dimension(59, 35));
        btn44.setMinimumSize(new java.awt.Dimension(59, 35));
        btn44.setPreferredSize(new java.awt.Dimension(59, 35));
        btn44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn44MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn44, gridBagConstraints);

        btn45.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn45.setMaximumSize(new java.awt.Dimension(59, 35));
        btn45.setMinimumSize(new java.awt.Dimension(59, 35));
        btn45.setPreferredSize(new java.awt.Dimension(59, 35));
        btn45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn45MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn45, gridBagConstraints);

        btn46.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn46.setMaximumSize(new java.awt.Dimension(59, 35));
        btn46.setMinimumSize(new java.awt.Dimension(59, 35));
        btn46.setPreferredSize(new java.awt.Dimension(59, 35));
        btn46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn46MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn46, gridBagConstraints);

        btn47.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn47.setMaximumSize(new java.awt.Dimension(59, 35));
        btn47.setMinimumSize(new java.awt.Dimension(59, 35));
        btn47.setPreferredSize(new java.awt.Dimension(59, 35));
        btn47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn47MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn47, gridBagConstraints);

        btn50.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn50.setMaximumSize(new java.awt.Dimension(59, 35));
        btn50.setMinimumSize(new java.awt.Dimension(59, 35));
        btn50.setPreferredSize(new java.awt.Dimension(59, 35));
        btn50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn50MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn50, gridBagConstraints);

        btn51.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn51.setMaximumSize(new java.awt.Dimension(59, 35));
        btn51.setMinimumSize(new java.awt.Dimension(59, 35));
        btn51.setPreferredSize(new java.awt.Dimension(59, 35));
        btn51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn51MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn51, gridBagConstraints);

        btn52.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn52.setMaximumSize(new java.awt.Dimension(59, 35));
        btn52.setMinimumSize(new java.awt.Dimension(59, 35));
        btn52.setPreferredSize(new java.awt.Dimension(59, 35));
        btn52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn52MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn52, gridBagConstraints);

        btn53.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn53.setMaximumSize(new java.awt.Dimension(59, 35));
        btn53.setMinimumSize(new java.awt.Dimension(59, 35));
        btn53.setPreferredSize(new java.awt.Dimension(59, 35));
        btn53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn53MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn53, gridBagConstraints);

        btn54.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn54.setMaximumSize(new java.awt.Dimension(59, 35));
        btn54.setMinimumSize(new java.awt.Dimension(59, 35));
        btn54.setPreferredSize(new java.awt.Dimension(59, 35));
        btn54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn54MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn54, gridBagConstraints);

        btn55.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn55.setMaximumSize(new java.awt.Dimension(59, 35));
        btn55.setMinimumSize(new java.awt.Dimension(59, 35));
        btn55.setPreferredSize(new java.awt.Dimension(59, 35));
        btn55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn55MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn55, gridBagConstraints);

        btn56.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn56.setMaximumSize(new java.awt.Dimension(59, 35));
        btn56.setMinimumSize(new java.awt.Dimension(59, 35));
        btn56.setPreferredSize(new java.awt.Dimension(59, 35));
        btn56.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn56MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn56, gridBagConstraints);

        btn57.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn57.setMaximumSize(new java.awt.Dimension(59, 35));
        btn57.setMinimumSize(new java.awt.Dimension(59, 35));
        btn57.setPreferredSize(new java.awt.Dimension(59, 35));
        btn57.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn57MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn57, gridBagConstraints);

        btn60.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn60.setMaximumSize(new java.awt.Dimension(59, 35));
        btn60.setMinimumSize(new java.awt.Dimension(59, 35));
        btn60.setPreferredSize(new java.awt.Dimension(59, 35));
        btn60.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn60MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn60, gridBagConstraints);

        btn61.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn61.setMaximumSize(new java.awt.Dimension(59, 35));
        btn61.setMinimumSize(new java.awt.Dimension(59, 35));
        btn61.setPreferredSize(new java.awt.Dimension(59, 35));
        btn61.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn61MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn61, gridBagConstraints);

        btn62.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn62.setMaximumSize(new java.awt.Dimension(59, 35));
        btn62.setMinimumSize(new java.awt.Dimension(59, 35));
        btn62.setPreferredSize(new java.awt.Dimension(59, 35));
        btn62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn62MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn62, gridBagConstraints);

        btn63.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn63.setMaximumSize(new java.awt.Dimension(59, 35));
        btn63.setMinimumSize(new java.awt.Dimension(59, 35));
        btn63.setPreferredSize(new java.awt.Dimension(59, 35));
        btn63.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn63MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn63, gridBagConstraints);

        btn64.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn64.setMaximumSize(new java.awt.Dimension(59, 35));
        btn64.setMinimumSize(new java.awt.Dimension(59, 35));
        btn64.setPreferredSize(new java.awt.Dimension(59, 35));
        btn64.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn64MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn64, gridBagConstraints);

        btn65.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn65.setMaximumSize(new java.awt.Dimension(59, 35));
        btn65.setMinimumSize(new java.awt.Dimension(59, 35));
        btn65.setPreferredSize(new java.awt.Dimension(59, 35));
        btn65.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn65MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn65, gridBagConstraints);

        btn66.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn66.setMaximumSize(new java.awt.Dimension(59, 35));
        btn66.setMinimumSize(new java.awt.Dimension(59, 35));
        btn66.setPreferredSize(new java.awt.Dimension(59, 35));
        btn66.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn66MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn66, gridBagConstraints);

        btn67.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn67.setMaximumSize(new java.awt.Dimension(59, 35));
        btn67.setMinimumSize(new java.awt.Dimension(59, 35));
        btn67.setPreferredSize(new java.awt.Dimension(59, 35));
        btn67.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn67MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn67, gridBagConstraints);

        btn70.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn70.setMaximumSize(new java.awt.Dimension(59, 35));
        btn70.setMinimumSize(new java.awt.Dimension(59, 35));
        btn70.setPreferredSize(new java.awt.Dimension(59, 35));
        btn70.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn70MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn70, gridBagConstraints);

        btn71.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn71.setMaximumSize(new java.awt.Dimension(59, 35));
        btn71.setMinimumSize(new java.awt.Dimension(59, 35));
        btn71.setPreferredSize(new java.awt.Dimension(59, 35));
        btn71.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn71MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn71, gridBagConstraints);

        btn72.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn72.setMaximumSize(new java.awt.Dimension(59, 35));
        btn72.setMinimumSize(new java.awt.Dimension(59, 35));
        btn72.setPreferredSize(new java.awt.Dimension(59, 35));
        btn72.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn72MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn72, gridBagConstraints);

        btn73.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn73.setMaximumSize(new java.awt.Dimension(59, 35));
        btn73.setMinimumSize(new java.awt.Dimension(59, 35));
        btn73.setPreferredSize(new java.awt.Dimension(59, 35));
        btn73.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn73MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn73, gridBagConstraints);

        btn74.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn74.setMaximumSize(new java.awt.Dimension(59, 35));
        btn74.setMinimumSize(new java.awt.Dimension(59, 35));
        btn74.setPreferredSize(new java.awt.Dimension(59, 35));
        btn74.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn74MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn74, gridBagConstraints);

        btn75.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn75.setMaximumSize(new java.awt.Dimension(59, 35));
        btn75.setMinimumSize(new java.awt.Dimension(59, 35));
        btn75.setPreferredSize(new java.awt.Dimension(59, 35));
        btn75.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn75MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn75, gridBagConstraints);

        btn76.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn76.setMaximumSize(new java.awt.Dimension(59, 35));
        btn76.setMinimumSize(new java.awt.Dimension(59, 35));
        btn76.setPreferredSize(new java.awt.Dimension(59, 35));
        btn76.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn76MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn76, gridBagConstraints);

        btn77.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn77.setMaximumSize(new java.awt.Dimension(59, 35));
        btn77.setMinimumSize(new java.awt.Dimension(59, 35));
        btn77.setPreferredSize(new java.awt.Dimension(59, 35));
        btn77.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn77MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn77, gridBagConstraints);

        btn20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn20.setMaximumSize(new java.awt.Dimension(59, 35));
        btn20.setMinimumSize(new java.awt.Dimension(59, 35));
        btn20.setPreferredSize(new java.awt.Dimension(59, 35));
        btn20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn20MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn20, gridBagConstraints);

        btn21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn21.setMaximumSize(new java.awt.Dimension(59, 35));
        btn21.setMinimumSize(new java.awt.Dimension(59, 35));
        btn21.setPreferredSize(new java.awt.Dimension(59, 35));
        btn21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn21MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn21, gridBagConstraints);

        btn22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn22.setMaximumSize(new java.awt.Dimension(59, 35));
        btn22.setMinimumSize(new java.awt.Dimension(59, 35));
        btn22.setPreferredSize(new java.awt.Dimension(59, 35));
        btn22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn22MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn22, gridBagConstraints);

        btn23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn23.setMaximumSize(new java.awt.Dimension(59, 35));
        btn23.setMinimumSize(new java.awt.Dimension(59, 35));
        btn23.setPreferredSize(new java.awt.Dimension(59, 35));
        btn23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn23MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn23, gridBagConstraints);

        btn24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn24.setMaximumSize(new java.awt.Dimension(59, 35));
        btn24.setMinimumSize(new java.awt.Dimension(59, 35));
        btn24.setPreferredSize(new java.awt.Dimension(59, 35));
        btn24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn24MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn24, gridBagConstraints);

        btn25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn25.setMaximumSize(new java.awt.Dimension(59, 35));
        btn25.setMinimumSize(new java.awt.Dimension(59, 35));
        btn25.setPreferredSize(new java.awt.Dimension(59, 35));
        btn25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn25MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn25, gridBagConstraints);

        btn26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn26.setMaximumSize(new java.awt.Dimension(59, 35));
        btn26.setMinimumSize(new java.awt.Dimension(59, 35));
        btn26.setPreferredSize(new java.awt.Dimension(59, 35));
        btn26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn26MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn26, gridBagConstraints);

        btn27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn27.setMaximumSize(new java.awt.Dimension(59, 35));
        btn27.setMinimumSize(new java.awt.Dimension(59, 35));
        btn27.setPreferredSize(new java.awt.Dimension(59, 35));
        btn27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn27MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn27, gridBagConstraints);

        btn10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn10.setMaximumSize(new java.awt.Dimension(59, 35));
        btn10.setMinimumSize(new java.awt.Dimension(59, 35));
        btn10.setPreferredSize(new java.awt.Dimension(59, 35));
        btn10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn10MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn10, gridBagConstraints);

        btn11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn11.setMaximumSize(new java.awt.Dimension(59, 35));
        btn11.setMinimumSize(new java.awt.Dimension(59, 35));
        btn11.setPreferredSize(new java.awt.Dimension(59, 35));
        btn11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn11MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn11, gridBagConstraints);

        btn12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn12.setMaximumSize(new java.awt.Dimension(59, 35));
        btn12.setMinimumSize(new java.awt.Dimension(59, 35));
        btn12.setPreferredSize(new java.awt.Dimension(59, 35));
        btn12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn12MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn12, gridBagConstraints);

        btn13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn13.setMaximumSize(new java.awt.Dimension(59, 35));
        btn13.setMinimumSize(new java.awt.Dimension(59, 35));
        btn13.setPreferredSize(new java.awt.Dimension(59, 35));
        btn13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn13MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn13, gridBagConstraints);

        btn14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn14.setMaximumSize(new java.awt.Dimension(59, 35));
        btn14.setMinimumSize(new java.awt.Dimension(59, 35));
        btn14.setPreferredSize(new java.awt.Dimension(59, 35));
        btn14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn14MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn14, gridBagConstraints);

        btn15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn15.setMaximumSize(new java.awt.Dimension(59, 35));
        btn15.setMinimumSize(new java.awt.Dimension(59, 35));
        btn15.setPreferredSize(new java.awt.Dimension(59, 35));
        btn15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn15MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn15, gridBagConstraints);

        btn16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn16.setMaximumSize(new java.awt.Dimension(59, 35));
        btn16.setMinimumSize(new java.awt.Dimension(59, 35));
        btn16.setPreferredSize(new java.awt.Dimension(59, 35));
        btn16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn16MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn16, gridBagConstraints);

        btn17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn17.setMaximumSize(new java.awt.Dimension(59, 35));
        btn17.setMinimumSize(new java.awt.Dimension(59, 35));
        btn17.setPreferredSize(new java.awt.Dimension(59, 35));
        btn17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn17MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tileGrid.add(btn17, gridBagConstraints);

        btn00.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn00.setMaximumSize(new java.awt.Dimension(59, 35));
        btn00.setMinimumSize(new java.awt.Dimension(59, 35));
        btn00.setPreferredSize(new java.awt.Dimension(59, 35));
        btn00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn00MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(48, 0, 0, 0);
        tileGrid.add(btn00, gridBagConstraints);

        btn01.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn01.setMaximumSize(new java.awt.Dimension(59, 35));
        btn01.setMinimumSize(new java.awt.Dimension(59, 35));
        btn01.setPreferredSize(new java.awt.Dimension(59, 35));
        btn01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn01MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(48, 0, 0, 0);
        tileGrid.add(btn01, gridBagConstraints);

        btn02.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn02.setMaximumSize(new java.awt.Dimension(59, 35));
        btn02.setMinimumSize(new java.awt.Dimension(59, 35));
        btn02.setPreferredSize(new java.awt.Dimension(59, 35));
        btn02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn02MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(48, 0, 0, 0);
        tileGrid.add(btn02, gridBagConstraints);

        btn03.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn03.setMaximumSize(new java.awt.Dimension(59, 35));
        btn03.setMinimumSize(new java.awt.Dimension(59, 35));
        btn03.setPreferredSize(new java.awt.Dimension(59, 35));
        btn03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn03MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(48, 0, 0, 0);
        tileGrid.add(btn03, gridBagConstraints);

        btn04.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn04.setMaximumSize(new java.awt.Dimension(59, 35));
        btn04.setMinimumSize(new java.awt.Dimension(59, 35));
        btn04.setPreferredSize(new java.awt.Dimension(59, 35));
        btn04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn04MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(48, 0, 0, 0);
        tileGrid.add(btn04, gridBagConstraints);

        btn05.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn05.setMaximumSize(new java.awt.Dimension(59, 35));
        btn05.setMinimumSize(new java.awt.Dimension(59, 35));
        btn05.setPreferredSize(new java.awt.Dimension(59, 35));
        btn05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn05MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(48, 0, 0, 0);
        tileGrid.add(btn05, gridBagConstraints);

        btn06.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn06.setMaximumSize(new java.awt.Dimension(59, 35));
        btn06.setMinimumSize(new java.awt.Dimension(59, 35));
        btn06.setPreferredSize(new java.awt.Dimension(59, 35));
        btn06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn06MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(48, 0, 0, 0);
        tileGrid.add(btn06, gridBagConstraints);

        btn07.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn07.setMaximumSize(new java.awt.Dimension(59, 35));
        btn07.setMinimumSize(new java.awt.Dimension(59, 35));
        btn07.setPreferredSize(new java.awt.Dimension(59, 35));
        btn07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn07MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(48, 0, 0, 0);
        tileGrid.add(btn07, gridBagConstraints);

        getContentPane().add(tileGrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 530, 530));
        tileGrid.getAccessibleContext().setAccessibleName("");
        tileGrid.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // All the methods below are to detect mouse clicks for each button on the board
    // and call the processClick method and pass the location of the button as parameters.
    private void btn00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn00MouseClicked
        processClick(0, 0, evt);
    }//GEN-LAST:event_btn00MouseClicked

    private void btn01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn01MouseClicked
        processClick(0, 1, evt);
    }//GEN-LAST:event_btn01MouseClicked

    private void btn02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn02MouseClicked
        processClick(0, 2, evt);
    }//GEN-LAST:event_btn02MouseClicked

    private void btn03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn03MouseClicked
        processClick(0, 3, evt);
    }//GEN-LAST:event_btn03MouseClicked

    private void btn04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn04MouseClicked
        processClick(0, 4, evt);
    }//GEN-LAST:event_btn04MouseClicked

    private void btn05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn05MouseClicked
        processClick(0, 5, evt);
    }//GEN-LAST:event_btn05MouseClicked

    private void btn06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn06MouseClicked
        processClick(0, 6, evt);
    }//GEN-LAST:event_btn06MouseClicked

    private void btn07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn07MouseClicked
        processClick(0, 7, evt);
    }//GEN-LAST:event_btn07MouseClicked

    private void btn10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn10MouseClicked
        processClick(1, 0, evt);
    }//GEN-LAST:event_btn10MouseClicked

    private void btn11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn11MouseClicked
        processClick(1, 1, evt);
    }//GEN-LAST:event_btn11MouseClicked

    private void btn12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn12MouseClicked
        processClick(1, 2, evt);
    }//GEN-LAST:event_btn12MouseClicked

    private void btn13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn13MouseClicked
        processClick(1, 3, evt);
    }//GEN-LAST:event_btn13MouseClicked

    private void btn14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn14MouseClicked
        processClick(1, 4, evt);
    }//GEN-LAST:event_btn14MouseClicked

    private void btn15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn15MouseClicked
        processClick(1, 5, evt);
    }//GEN-LAST:event_btn15MouseClicked

    private void btn16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn16MouseClicked
        processClick(1, 6, evt);
    }//GEN-LAST:event_btn16MouseClicked

    private void btn17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn17MouseClicked
        processClick(1, 7, evt);
    }//GEN-LAST:event_btn17MouseClicked

    private void btn20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn20MouseClicked
        processClick(2, 0, evt);
    }//GEN-LAST:event_btn20MouseClicked

    private void btn21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn21MouseClicked
        processClick(2, 1, evt);
    }//GEN-LAST:event_btn21MouseClicked

    private void btn22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn22MouseClicked
        processClick(2, 2, evt);
    }//GEN-LAST:event_btn22MouseClicked

    private void btn23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn23MouseClicked
        processClick(2, 3, evt);
    }//GEN-LAST:event_btn23MouseClicked

    private void btn24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn24MouseClicked
        processClick(2, 4, evt);
    }//GEN-LAST:event_btn24MouseClicked

    private void btn25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn25MouseClicked
        processClick(2, 5, evt);
    }//GEN-LAST:event_btn25MouseClicked

    private void btn26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn26MouseClicked
        processClick(2, 6, evt);
    }//GEN-LAST:event_btn26MouseClicked

    private void btn27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn27MouseClicked
        processClick(2, 7, evt);
    }//GEN-LAST:event_btn27MouseClicked

    private void btn30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn30MouseClicked
        processClick(3, 0, evt);
    }//GEN-LAST:event_btn30MouseClicked

    private void btn31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn31MouseClicked
        processClick(3, 1, evt);
    }//GEN-LAST:event_btn31MouseClicked

    private void btn32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn32MouseClicked
        processClick(3, 2, evt);
    }//GEN-LAST:event_btn32MouseClicked

    private void btn33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn33MouseClicked
        processClick(3, 3, evt);
    }//GEN-LAST:event_btn33MouseClicked

    private void btn34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn34MouseClicked
        processClick(3, 4, evt);
    }//GEN-LAST:event_btn34MouseClicked

    private void btn35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn35MouseClicked
        processClick(3, 5, evt);
    }//GEN-LAST:event_btn35MouseClicked

    private void btn36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn36MouseClicked
        processClick(3, 6, evt);
    }//GEN-LAST:event_btn36MouseClicked

    private void btn37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn37MouseClicked
        processClick(3, 7, evt);
    }//GEN-LAST:event_btn37MouseClicked

    private void btn40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn40MouseClicked
        processClick(4, 0, evt);
    }//GEN-LAST:event_btn40MouseClicked

    private void btn41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn41MouseClicked
        processClick(4, 1, evt);
    }//GEN-LAST:event_btn41MouseClicked

    private void btn42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn42MouseClicked
        processClick(4, 2, evt);
    }//GEN-LAST:event_btn42MouseClicked

    private void btn43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn43MouseClicked
        processClick(4, 3, evt);
    }//GEN-LAST:event_btn43MouseClicked

    private void btn44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn44MouseClicked
        processClick(4, 4, evt);
    }//GEN-LAST:event_btn44MouseClicked

    private void btn45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn45MouseClicked
        processClick(4, 5, evt);
    }//GEN-LAST:event_btn45MouseClicked

    private void btn46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn46MouseClicked
        processClick(4, 6, evt);
    }//GEN-LAST:event_btn46MouseClicked

    private void btn47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn47MouseClicked
        processClick(4, 7, evt);
    }//GEN-LAST:event_btn47MouseClicked

    private void btn50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn50MouseClicked
        processClick(5, 0, evt);
    }//GEN-LAST:event_btn50MouseClicked

    private void btn51MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn51MouseClicked
        processClick(5, 1, evt);
    }//GEN-LAST:event_btn51MouseClicked

    private void btn52MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn52MouseClicked
        processClick(5, 2, evt);
    }//GEN-LAST:event_btn52MouseClicked

    private void btn53MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn53MouseClicked
        processClick(5, 3, evt);
    }//GEN-LAST:event_btn53MouseClicked

    private void btn54MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn54MouseClicked
        processClick(5, 4, evt);
    }//GEN-LAST:event_btn54MouseClicked

    private void btn55MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn55MouseClicked
        processClick(5, 5, evt);
    }//GEN-LAST:event_btn55MouseClicked

    private void btn56MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn56MouseClicked
        processClick(5, 6, evt);
    }//GEN-LAST:event_btn56MouseClicked

    private void btn57MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn57MouseClicked
        processClick(5, 7, evt);
    }//GEN-LAST:event_btn57MouseClicked

    private void btn60MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn60MouseClicked
        processClick(6, 0, evt);
    }//GEN-LAST:event_btn60MouseClicked

    private void btn61MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn61MouseClicked
        processClick(6, 1, evt);
    }//GEN-LAST:event_btn61MouseClicked

    private void btn62MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn62MouseClicked
        processClick(6, 2, evt);
    }//GEN-LAST:event_btn62MouseClicked

    private void btn63MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn63MouseClicked
        processClick(6, 3, evt);
    }//GEN-LAST:event_btn63MouseClicked

    private void btn64MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn64MouseClicked
        processClick(6, 4, evt);
    }//GEN-LAST:event_btn64MouseClicked

    private void btn65MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn65MouseClicked
        processClick(6, 5, evt);
    }//GEN-LAST:event_btn65MouseClicked

    private void btn66MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn66MouseClicked
        processClick(6, 6, evt);
    }//GEN-LAST:event_btn66MouseClicked

    private void btn67MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn67MouseClicked
        processClick(6, 7, evt);
    }//GEN-LAST:event_btn67MouseClicked

    private void btn70MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn70MouseClicked
        processClick(7, 0, evt);
    }//GEN-LAST:event_btn70MouseClicked

    private void btn71MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn71MouseClicked
        processClick(7, 1, evt);
    }//GEN-LAST:event_btn71MouseClicked

    private void btn72MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn72MouseClicked
        processClick(7, 2, evt);
    }//GEN-LAST:event_btn72MouseClicked

    private void btn73MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn73MouseClicked
        processClick(7, 3, evt);
    }//GEN-LAST:event_btn73MouseClicked

    private void btn74MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn74MouseClicked
        processClick(7, 4, evt);
    }//GEN-LAST:event_btn74MouseClicked

    private void btn75MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn75MouseClicked
        processClick(7, 5, evt);
    }//GEN-LAST:event_btn75MouseClicked

    private void btn76MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn76MouseClicked
        processClick(7, 6, evt);
    }//GEN-LAST:event_btn76MouseClicked

    private void btn77MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn77MouseClicked
        processClick(7, 7, evt);
    }//GEN-LAST:event_btn77MouseClicked

    /**
     * This method resets the game when the "reset" button is clicked
     */
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // Reset variable values
        numFlags = 10;
        firstMove = true;
        safeBlocks = 54;
        lblFlags.setText("Flags: " + numFlags);

        // Loop through each button
        for (int i = 0; i < 8; i++) {
            for (int j = 0; j < 8; j++) {
                // Remove any icons
                board[i][j].setIcon(null);
                // Set the color of the block back to green
                board[i][j].setBackground(Color.GREEN);
                // Remove any text
                board[i][j].setText("");
                // Remove text color
                board[i][j].setForeground(Color.BLACK);
                // Remove any landmines
                mineField[i][j] = false;
            }
        }
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * This method closes the game when the "exit" button is clicked
     */
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * This method processes the mouse clicks on a certain button on the board
     *
     * @param i - an integer representing the row index
     * @param j - an integer representing the column index
     * @param evt - a MouseEvent object used to detect the exact button that was
     * clicked
     */
    public void processClick(int i, int j, MouseEvent evt) {
        // If user right-clicks and there is no icon on the block
        if (evt.getButton() == MouseEvent.BUTTON3 && board[i][j].getIcon() == null && board[i][j].getBackground() == Color.GREEN) {
            // Check if user can place anymore flags
            if (numFlags > 0) {
                // Set preffered size so icon doesn't change height or width of block
                board[i][j].setPreferredSize(new Dimension(59, 35));
                // Place the flag icon
                board[i][j].setIcon(flagIcon);
                // Decrease the number of flags by one
                numFlags--;
                // Display to user the number of remaining flags
                lblFlags.setText("Flags: " + numFlags);
            }

        } // If user right-clicks and there is already a flag icon on the block
        else if (evt.getButton() == MouseEvent.BUTTON3 && board[i][j].getIcon() != null) {
            // Remove the flag icon
            board[i][j].setIcon(null);
            // Increase the number of flags by one
            numFlags++;
            // Display to user
            lblFlags.setText("Flags: " + numFlags);
        }

        // If user left-clicks on a non-flagged block
        if (evt.getButton() == MouseEvent.BUTTON1 && board[i][j].getIcon() == null) {

            // If it is the user's first move
            if (firstMove) {
                // Loop through the neighbouring blocks
                for (int r = -1; r < 2; r++) {
                    for (int c = -1; c < 2; c++) {
                        // If neighbour is within the board
                        if (isValid(i + r, j + c)) {
                            // Set them as landmines so there are no landmines
                            // next to the user's first click (also user can't lose on first move)
                            mineField[i + r][j + c] = true;
                        }
                    }
                }

                // Place the actual landmines on the board
                populateMineField();

                // Loop through the neighbouring mines again
                for (int r = -1; r < 2; r++) {
                    for (int c = -1; c < 2; c++) {
                        // If neighbour is within the board
                        if (isValid(i + r, j + c)) {
                            // Set them as safe blocks
                            mineField[i + r][j + c] = false;
                        }
                    }
                }

                // No longer the user's first move
                firstMove = false;
            }

            // If user clicks on a bomb
            if (mineField[i][j]) {
                // user loses
                endGame("loss");
                return;
            }

            // Otherwise clear the blocks
            clearTiles(i, j);
        }
    }

    /**
     * This recursive method clears the board and displays the clues of
     * neighboring bombs to the user.
     *
     * @param i - an integer representing the row index
     * @param j - an integer representing the column index
     */
    public void clearTiles(int i, int j) {
        // If the block has not been cleared (is a green block)
        if (board[i][j].getBackground() == Color.GREEN) {
            // subtract the number of safe blocks by one
            safeBlocks--;
            // set the color of the block to light gray
            board[i][j].setBackground(Color.LIGHT_GRAY);

            // If there are no more safe blocks
            if (safeBlocks == 0) {
                // User wins
                endGame("win");
                return;
            }
            
            // Store the number of neighbouring bombs for the block
            int numBombs = numNeighbouringBombs(i, j);

            // Otherwise if there are no neighbouring landmines
            if (numBombs == 0) {
                // Loop through all the neighbours including the original block
                for (int r = -1; r < 2; r++) {
                    for (int c = -1; c < 2; c++) {
                        // Skip the original block
                        if (r == 0 && c == 0) {
                            continue;
                        }
                        // If neighbouring block is on the board and is not a bomb
                        if (isValid(i + r, j + c) && mineField[i + r][j + c] == false) {
                            // If there is a flag
                            if (board[i + r][j + c].getIcon() != null) {
                                // Remove it
                                board[i + r][j + c].setIcon(null);
                                // Increase number of flags and display to user
                                numFlags++;
                                lblFlags.setText("Flags: " + numFlags);
                            }

                            // Call itself with the location of the next block
                            clearTiles(i + r, j + c);
                        }
                    }
                }
            } // Otherwise there is a neighbouring landmine
            else {
                board[i][j].setPreferredSize(new Dimension(59, 35));
                // Set the number of neighbouring mines on the screen and stop searching
                board[i][j].setText("" + numNeighbouringBombs(i, j));
                
                // If there is one neighbouring bomb
                if (numBombs == 1) {
                    // Set the text color to yellow
                    board[i][j].setForeground(Color.YELLOW);
                }
                // If there are two neighbouring bombs 
                else if (numBombs == 2) {
                    // Set the text color to orange
                    board[i][j].setForeground(Color.ORANGE);
                }
                // Otherwise there are 3 or more neighbouring bombs
                else{
                    // Set text color to red
                    board[i][j].setForeground(Color.RED);
                }
            }
            
        }
    }
        /**
         * This method randomly places landmines on the board
         */
    public void populateMineField() {
        // Create a random object
        Random r = new Random();
        int i, j;

        // Loop 10 times to place 10 landmines
        for (int k = 0; k < 10; k++) {
            // Generate random indices
            i = r.nextInt(8);
            j = r.nextInt(8);

            // If the randomly generated indices fall on a bomb
            if (mineField[i][j] == true) {
                // Decrease loop counter to try again
                k--;
            } // Otherwise make the block a landmine
            else {
                mineField[i][j] = true;
            }
        }
    }

    /**
     * This method checks if a block is inside of the board
     *
     * @param i - an integer representing the row index
     * @param j - an integer representing the column index
     * @return - whether the block is within the board's boundaries
     */
    public boolean isValid(int i, int j) {
        return (i >= 0 && i < 8) && (j >= 0 && j < 8);
    }

    /**
     * This method displays a message for the user when they win or lose
     *
     * @param outcome - a string dictating whether the user lost or won
     */
    public void endGame(String outcome) {
        // Loop through all the blocks
        for (int r = 0; r < 8; r++) {
            for (int c = 0; c < 8; c++) {
                // If it is a landmine
                if (mineField[r][c]) {
                    // Set the bomb icon to display to the user where the 
                    // bombs were hidden
                    board[r][c].setIcon(bombIcon);
                }
            }
        }

        // If the user lost
        if (outcome.equals("loss")) {
            // Display a message telling the user they lost
            JOptionPane.showMessageDialog(null, "You LOSE!", "Game Over", JOptionPane.INFORMATION_MESSAGE);
        } // Otherwise the user won
        else {
            // Display a message telling the user they won
            JOptionPane.showMessageDialog(null, "You WIN!", "Game Over", JOptionPane.INFORMATION_MESSAGE);
        }

        // Reset the game by clicking the reset button
        btnReset.doClick();
    }

    /**
     * This method determines the number of landmines that a specific block has
     *
     * @param row - an integer representing the row index
     * @param col - an integer representing the column index
     * @return - an integer about the number of neighboring landmines
     */
    public int numNeighbouringBombs(int row, int col) {
        // Set counter to 0
        int cnt = 0;

        // Loop through all the neighbouring blocks
        for (int r = -1; r < 2; r++) {
            for (int c = -1; c < 2; c++) {
                // If it is within the board and there is a landmine
                if (isValid(row + r, col + c) && mineField[row + r][col + c] == true) {
                    // Increase the counter by one
                    cnt++;
                }
            }
        }
        return cnt;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Minesweeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Minesweeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Minesweeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Minesweeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Minesweeper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuBar;
    private javax.swing.JButton btn00;
    private javax.swing.JButton btn01;
    private javax.swing.JButton btn02;
    private javax.swing.JButton btn03;
    private javax.swing.JButton btn04;
    private javax.swing.JButton btn05;
    private javax.swing.JButton btn06;
    private javax.swing.JButton btn07;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn17;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btn23;
    private javax.swing.JButton btn24;
    private javax.swing.JButton btn25;
    private javax.swing.JButton btn26;
    private javax.swing.JButton btn27;
    private javax.swing.JButton btn30;
    private javax.swing.JButton btn31;
    private javax.swing.JButton btn32;
    private javax.swing.JButton btn33;
    private javax.swing.JButton btn34;
    private javax.swing.JButton btn35;
    private javax.swing.JButton btn36;
    private javax.swing.JButton btn37;
    private javax.swing.JButton btn40;
    private javax.swing.JButton btn41;
    private javax.swing.JButton btn42;
    private javax.swing.JButton btn43;
    private javax.swing.JButton btn44;
    private javax.swing.JButton btn45;
    private javax.swing.JButton btn46;
    private javax.swing.JButton btn47;
    private javax.swing.JButton btn50;
    private javax.swing.JButton btn51;
    private javax.swing.JButton btn52;
    private javax.swing.JButton btn53;
    private javax.swing.JButton btn54;
    private javax.swing.JButton btn55;
    private javax.swing.JButton btn56;
    private javax.swing.JButton btn57;
    private javax.swing.JButton btn60;
    private javax.swing.JButton btn61;
    private javax.swing.JButton btn62;
    private javax.swing.JButton btn63;
    private javax.swing.JButton btn64;
    private javax.swing.JButton btn65;
    private javax.swing.JButton btn66;
    private javax.swing.JButton btn67;
    private javax.swing.JButton btn70;
    private javax.swing.JButton btn71;
    private javax.swing.JButton btn72;
    private javax.swing.JButton btn73;
    private javax.swing.JButton btn74;
    private javax.swing.JButton btn75;
    private javax.swing.JButton btn76;
    private javax.swing.JButton btn77;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel lblFlags;
    private javax.swing.JLabel lblInstructions;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel tileGrid;
    // End of variables declaration//GEN-END:variables
}
